name: dataset-notifier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81

    - name: Cache binary
      uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe
      env:
        cache-name: cache-built-binary
      with:
        path: bin/dataset-tweeter
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('dataset-tweeter') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: build binary
      run: |
        mkdir -p bin
        ls -l bin
        go -ldflags="-s -w" -o bin/dataset-tweeter build main.go

        #    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5
        #      name: Persist binary
        #      with:
        #        name: dataset-tweeter-artifact
        #        path: dataset-tweeter

    - name: Run a multi-line script
      run: |
        ./main
        echo "yolo" > test.txt

    - name: Print a secret
      run: echo ${{ secrets.SUPER_SECRET }}
