name: dataset-notifier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81

    - name: build binary
      run: |
        mkdir -p bin
        ls -l bin
        go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - name: Install mc
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc

    - name: Execute
      run: ./bin/dataset-tweeter

    - name: Print a secret
      run: echo ${{ secrets.SUPER_SECRET }}
