name: dataset-notifier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81

    - name: Cache binary
      uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe
      env:
        cache-name: cache-built-binary
      with:
        path: bin/dataset-tweeter
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('dataset-tweeter') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: build binary
      run: |
        mkdir -p bin
        ls -l bin
        go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - uses: actions/download-artifact@v1
      with:
        name: previous-datasets-artifact

    - name: ls
      run: ls -lah

#    - name: Removeme Create a dummy file
#      run: echo '{}' > data-yesterday.json
#
#    - uses: actions/upload-artifact@v1
#      with:
#        name: previous-datasets-artifact
#        path: data-yesterday.json

    - name: Execute the binary
      run: |
        mkdir -p data
        ./bin/dataset-tweeter

    - name: Print a secret
      run: echo ${{ secrets.SUPER_SECRET }}
